### ISSUE TITLE
error

### ISSUE THREAD

**Issue by MGTV01** [Ennyolajide/Dotcoin-auto-mine#2]
![image](https://github.com/Ennyolajide/Dotcoin-auto-mine/assets/125827172/47d43e3e-deb7-477e-af89-3aed995b0c75)
Hello. How can I solve this problem? What is the format of the .env file? I have set all the models, but we have all encountered this error.

**Comment by Ennyolajide** [comment]
<img width="1048" alt="Screenshot 2024-06-10 at 20 45 26" src="https://github.com/Ennyolajide/Dotcoin-auto-mine/assets/21691999/aaff0054-eaff-403c-a167-fce437694be4">

this format

**Comment by MGTV01** [comment]
> <img alt="اسکرین شات 2024-06-10 در 20 45 26" width="1048" src="https://private-user-images.githubusercontent.com/21691999/338322323-aaff0054-eaff-403c-a167-fce437694be4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwNDk0MDEsIm5iZiI6MTcxODA0OTEwMSwicGF0aCI6Ii8yMTY5MTk5OS8zMzgzMjIzMjMtYWFmZjAwNTQtZWFmZi00MDNjLWExNjctZmNlNDM3Njk0YmU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEwVDE5NTE0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjYTJhYzFhZGY5YjMwN2E0NjNiY2FjZTdiOTk5NDcyOGY0ZDZmODZhOGViMTI5OGRlNjRiZTdlMzAzNzgzYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gfTGOYvZawdeAfOLzEx7jZINrFqjc4ieZQ187EmYsZ8">
> این فرمت

![image](https://github.com/Ennyolajide/Dotcoin-auto-mine/assets/125827172/dc177984-5828-419c-883a-58da449d3c2f)
How

**Comment by Ennyolajide** [comment]
get the bearer token and the API token

**Comment by MGTV01** [comment]
> get the bearer token and the API token

How do I receive?

**Comment by Ennyolajide** [comment]
I cant teach that here

**Comment by MGTV01** [comment]
> من نمیتونم اینجا یاد بدم

Tanx bro

**Comment by Ennyolajide** [comment]
You can contact me on telegram 

> > من نمیتونم اینجا یاد بدم
> 
> Tanx bro

You're welcome 
Chat me on telegram for futher explanation
